// Generated by CoffeeScript 1.7.1
(function() {
  var sumMultiples, sum_5_or_7, sum_to_n;

  sum_5_or_7 = function(start, end) {
    if (start > end) {
      return 0;
    } else {
      if (start % 5 === 0 || start % 7 === 0) {
        return start + sum_5_or_7(start + 1, end);
      } else {
        return sum_5_or_7(start + 1, end);
      }
    }
  };

  console.log(sum_5_or_7(0, 2013));

  sum_to_n = function(n) {
    return n * (n + 1) / 2;
  };

  sumMultiples = function(limit, a) {
    return sum_to_n(Math.floor((limit - 1) / a)) * a;
  };

  console.log(sumMultiples(2013, 5) + sumMultiples(2013, 7) - sumMultiples(2013, 35));

}).call(this);
