// Generated by CoffeeScript 1.7.0
(function() {
  var sum_5_or_7;

  sum_5_or_7 = function(start, end) {
    if (start > end) {
      return 0;
    } else {
      if (start % 5 === 0 || start % 7 === 0) {
        return start + sum_5_or_7(start + 1, end);
      } else {
        return sum_5_or_7(start + 1, end);
      }
    }
  };

  console.log(sum_5_or_7(0, 2013));

}).call(this);
