// Generated by CoffeeScript 1.7.0
(function() {
  var generate_fibo, sum_odd;

  generate_fibo = function(list, limit) {
    var last, next, previous;
    previous = list[list.length - 2];
    last = list[list.length - 1];
    next = previous + last;
    if (next > limit) {
      return list;
    } else {
      return generate_fibo(list.concat([next]), limit);
    }
  };

  sum_odd = function(lst) {
    var el, total, _i, _len;
    total = 0;
    for (_i = 0, _len = lst.length; _i < _len; _i++) {
      el = lst[_i];
      if (el % 2 !== 0) {
        total += el;
      }
    }
    return total;
  };

  console.log(sum_odd(generate_fibo([1, 1], 4000000)));

}).call(this);
